"use client";

import { useEffect, useState, useCallback } from "react";
import {
  FileText,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  Download,
} from "lucide-react";
import { api } from "@/lib/api";
import type { Report } from "@/lib/types";
import ReportViewer from "@/components/reports/ReportViewer";
import SeverityBadge from "@/components/incidents/SeverityBadge";
import { formatDate } from "@/lib/utils";

const PAGE_SIZE = 20;

export default function ReportsPage() {
  const [reports, setReports] = useState<Report[]>([]);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(1);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [expandedId, setExpandedId] = useState<string | null>(null);

  const totalPages = Math.max(1, Math.ceil(total / PAGE_SIZE));

  const fetchReports = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const response = await api.getReports({ page, page_size: PAGE_SIZE });
      setReports(response.items);
      setTotal(response.total);
    } catch (err) {
      setError(
        err instanceof Error ? err.message : "Failed to fetch reports"
      );
    } finally {
      setLoading(false);
    }
  }, [page]);

  useEffect(() => {
    fetchReports();
  }, [fetchReports]);

  function toggleExpand(id: string) {
    setExpandedId(expandedId === id ? null : id);
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <FileText className="h-5 w-5 text-gray-500" />
          <span className="text-sm text-gray-400">
            <span className="font-semibold text-gray-100">{total}</span>{" "}
            generated reports
          </span>
        </div>
      </div>

      {/* Error */}
      {error && (
        <div className="rounded-lg border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-400">
          {error}
        </div>
      )}

      {/* Reports Table / List */}
      <div className="rounded-lg border border-surface-border bg-surface-card overflow-hidden">
        {loading ? (
          <div className="space-y-0">
            {[...Array(5)].map((_, i) => (
              <div
                key={i}
                className="flex items-center gap-4 border-b border-surface-border p-4"
              >
                <div className="h-4 w-32 animate-pulse rounded bg-surface-elevated" />
                <div className="h-4 w-20 animate-pulse rounded bg-surface-elevated" />
                <div className="h-4 flex-1 animate-pulse rounded bg-surface-elevated" />
              </div>
            ))}
          </div>
        ) : reports.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-16 text-gray-500">
            <FileText className="h-12 w-12 mb-3 opacity-50" />
            <p className="text-sm font-medium">No reports generated yet</p>
            <p className="text-xs mt-1">
              Reports are auto-generated when incidents are detected.
            </p>
          </div>
        ) : (
          <div>
            {/* Table header */}
            <div className="grid grid-cols-12 gap-4 border-b border-surface-border px-4 py-3 text-xs font-semibold text-gray-500 uppercase tracking-wider">
              <div className="col-span-3">Report Type</div>
              <div className="col-span-2">Generated By</div>
              <div className="col-span-2">Version</div>
              <div className="col-span-3">Created At</div>
              <div className="col-span-2 text-right">Actions</div>
            </div>

            {/* Rows */}
            {reports.map((report) => (
              <div key={report.id}>
                <div
                  className="grid grid-cols-12 gap-4 items-center border-b border-surface-border px-4 py-3 hover:bg-surface-elevated transition-colors cursor-pointer"
                  onClick={() => toggleExpand(report.id)}
                >
                  <div className="col-span-3">
                    <span className="text-sm font-medium text-gray-100 capitalize">
                      {report.report_type.replace(/_/g, " ")}
                    </span>
                  </div>
                  <div className="col-span-2">
                    <span className="text-sm text-gray-400">
                      {report.generated_by}
                    </span>
                  </div>
                  <div className="col-span-2">
                    <span className="text-sm text-gray-400">
                      v{report.version}
                    </span>
                  </div>
                  <div className="col-span-3">
                    <span className="text-sm text-gray-400">
                      {formatDate(report.created_at)}
                    </span>
                  </div>
                  <div className="col-span-2 flex items-center justify-end gap-2">
                    {report.pdf_url && (
                      <a
                        href={report.pdf_url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="rounded p-1 text-gray-400 hover:text-gray-100 hover:bg-surface-elevated transition-colors"
                        onClick={(e) => e.stopPropagation()}
                        title="Download PDF"
                      >
                        <Download className="h-4 w-4" />
                      </a>
                    )}
                    <button className="rounded p-1 text-gray-400 hover:text-gray-100 hover:bg-surface-elevated transition-colors">
                      {expandedId === report.id ? (
                        <ChevronUp className="h-4 w-4" />
                      ) : (
                        <ChevronDown className="h-4 w-4" />
                      )}
                    </button>
                  </div>
                </div>

                {/* Expanded Report Viewer */}
                {expandedId === report.id && (
                  <div className="border-b border-surface-border bg-surface-elevated/50 p-5">
                    <ReportViewer report={report} />
                  </div>
                )}
              </div>
            ))}
          </div>
        )}

        {/* Pagination */}
        {total > PAGE_SIZE && (
          <div className="flex items-center justify-between border-t border-surface-border px-4 py-3">
            <span className="text-xs text-gray-500">
              Page {page} of {totalPages}
            </span>
            <div className="flex items-center gap-2">
              <button
                onClick={() => setPage((p) => Math.max(1, p - 1))}
                disabled={page === 1}
                className="flex items-center gap-1 rounded-lg border border-surface-border px-3 py-1.5 text-xs text-gray-400 hover:bg-surface-elevated disabled:opacity-50 disabled:cursor-not-allowed"
              >
                <ChevronLeft className="h-3.5 w-3.5" />
                Previous
              </button>
              <button
                onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
                disabled={page === totalPages}
                className="flex items-center gap-1 rounded-lg border border-surface-border px-3 py-1.5 text-xs text-gray-400 hover:bg-surface-elevated disabled:opacity-50 disabled:cursor-not-allowed"
              >
                Next
                <ChevronRight className="h-3.5 w-3.5" />
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
